### ISSUE TITLE
Enumerable::from throws InvalidArgumentException on SimpleXMLElement

### ISSUE THREAD

**Issue by MatkovIvan** [Athari/YaLinqo#13]
When I tried call `Enumerable::from` on `SimpleXMLElement` throws

> InvalidArgumentException: source must be array or Traversable or Enumerable.

But class SimpleXMLElement implements Traversable.

**Comment by Athari** [comment]
Should work now. Please note that `SimpleXMLElement` returns element names as keys, so some transformations may return unexpected results, for example, a call to `toArray` will return just last elements of each name if multiple elements with the same name are present, because keys will collapse (`toList` can be used in this case to avoid the problem).
