### ISSUE TITLE
Version 3 doesn't exist

### ISSUE THREAD

**Issue by Bilge** [Athari/YaLinqo#35]
The documentation claims: Add to `composer.json`: `"athari/yalinqo": "^3.0"`. However, version 3 does not exist.

>    - The requested package athari/yalinqo ^3 exists as athari/yalinqo[dev-master, 2.x-dev, v1.0.0.0, v1.0.1.0, v1.0.1.1, v1.0.x-dev, v1.1.0.0, v1.1.1, v1.1.2, v2.0.0.0, v2.0.x-dev, v2.1.0.0, v2.2.0.0, v2.3.0.0, v2.3.1, v2.4.0, v2.4.1] but these are rejected by your constraint.

**Comment by Athari** [comment]
You should use `^2`. I'm currently developing v3.0 in the master branch. It's early pre-alpha and no tagged releases exist yet. The problem is, there's no way to tell GitHub to show ReadMe of the stable 2.0 branch. I guess I'll have to revert changes to ReadMe in the meantime.

**Comment by Bilge** [comment]
May I suggest you don't work in master. Work on a feature branch and merge 3.0 when it's ready.

**Comment by Athari** [comment]
@Bilge Less branches, less problems. YaLinqo's history is very linear, I'm the only actual developer, and I'm not going to pretend otherwise. The only reason I created branches for major versions is that third-party services require updates to their configs. YaLinqo has no bugs, no feature reqeusts, no pull requests, no nothing. If it ever changes, I may reconsider my approach.

Anyway, fixed ReadMe.

**Comment by Bilge** [comment]
I fail to see how anything you just mentioned is in any way relevant. If your approach was perfect this issue wouldn't exist.

**Comment by Athari** [comment]
@Bilge I don't see any issues. The only issue is that I updated ReadMe too early. Branching is irrelevant.
